### ISSUE TITLE
Add an asteric text to PDF print section

### ISSUE THREAD

**Issue by mw44118** [216software/Profiles#10]
Right now, asterisks are explained in footnotes at bottom of page.  Instead, we should have an icon that opens these.

**Comment by aprilhirsh** [comment]
Let's call these data notes. In the Rhode Island and Pittsburgh versions of the site, they use a pop-up with an "i" icon to give the user additional information about the data. This will allow us to put the relevant data notes right alongside the indicator instead of all at the bottom.
We will have to write a lot of these for you, though we can likely take some of the info from the Pittsburgh and Rhode Island sites where the indicator is derived from US Census and ACS data.
![data notes](https://cloud.githubusercontent.com/assets/7606957/17700383/85d52064-6393-11e6-98ba-b4fe7dbb8056.JPG)

**Comment by bormesh** [comment]
I've added these on the http://profiles.216software.com/#/stabilization?location_uuid=4ce7e0a3-9c63-4e21-a9dc-20b3ccf10346 page. Please look check them out there -- we can change as needed.

**Comment by bormesh** [comment]
When printing PDF, these info links should be brought in as footnotes to the pdf document.
